#ifndef __VIOLET_ERROR_H__
#define __VIOLET_ERROR_H__

#define  VIOLET_SUCCESS                         0
#define  VIOLET_ERROR_UNKNOWN                  (-1)

//通用错误;
#define  VIOLET_GENERAL_ERROR_BEGIN            (-10)
#define  VIOLET_ERROR_BAD_PARAM                (VIOLET_GENERAL_ERROR_BEGIN -1)
#define  VIOLET_ERROR_NULL_POINTER             (VIOLET_GENERAL_ERROR_BEGIN -2)
#define  VIOLET_ERROR_QUEUE_FULL               (VIOLET_GENERAL_ERROR_BEGIN -3)
#define  VIOLET_ERROR_QUEUE_EMPTY              (VIOLET_GENERAL_ERROR_BEGIN -4)
#define  VIOLET_ERROR_BAD_ENVIROUMENT          (VIOLET_GENERAL_ERROR_BEGIN -5)
#define  VIOLET_ERROR_NOT_READY                (VIOLET_GENERAL_ERROR_BEGIN -6)
#define  VIOLET_ERROR_BAD_LENGTH               (VIOLET_GENERAL_ERROR_BEGIN -7)
#define  VIOLET_ERROR_MAX_CONNECTED            (VIOLET_GENERAL_ERROR_BEGIN -8)
#define  VIOLET_ERROR_NOT_ENOUGH_MEM           (VIOLET_GENERAL_ERROR_BEGIN -9)
#define  VIOLET_ERROR_THREAD_CREATED_FAILED    (VIOLET_GENERAL_ERROR_BEGIN -10)
#define  VIOLET_ERROR_THREAD_RUNNING           (VIOLET_GENERAL_ERROR_BEGIN -11)
#define  VIOLET_ERROR_DEVICE_NOT_SUPPORT       (VIOLET_GENERAL_ERROR_BEGIN -12)
#define  VIOLET_ERROR_HARDWARE                 (VIOLET_GENERAL_ERROR_BEGIN -13)
#define  VIOLET_ERROR_COM_OPEN_FAILED          (VIOLET_GENERAL_ERROR_BEGIN -14)
#define  VIOLET_ERROR_COM_OPERATE_FAILED       (VIOLET_GENERAL_ERROR_BEGIN -15)
#define  VIOLET_ERROR_COM_USED                 (VIOLET_GENERAL_ERROR_BEGIN -16)
#define  VIOLET_ERROR_DEVICE_BUSY              (VIOLET_GENERAL_ERROR_BEGIN -17)
#define  VIOLET_ERROR_NOT_FOUND                (VIOLET_GENERAL_ERROR_BEGIN -18)
#define  VIOLET_ERROR_DEVICE_OPERATE_FAILED    (VIOLET_GENERAL_ERROR_BEGIN -19)

//网络错误
#define VIOLET_ERROR_NETWORK_BEGIN   			     (-100)
#define VIOLET_ERROR_SOCKET_CREATE_FAILED		   (VIOLET_ERROR_NETWORK_BEGIN -1)
#define VIOLET_ERROR_SOCKET_CONNECT_FAILED		 (VIOLET_ERROR_NETWORK_BEGIN -2)
#define VIOLET_ERROR_SOCKET_LISTEN_FAILED		   (VIOLET_ERROR_NETWORK_BEGIN -3)	
#define VIOLET_ERROR_SOCKET_ACCEPT_FAILED		   (VIOLET_ERROR_NETWORK_BEGIN -4)	
#define VIOLET_ERROR_SOCKET_CONNECT_TIMEOUT	   (VIOLET_ERROR_NETWORK_BEGIN -5)
#define VIOLET_ERROR_SOCKET_ACCEPT_TIMEOUT		 (VIOLET_ERROR_NETWORK_BEGIN -6)
#define VIOLET_ERROR_SOCKET_RECV_FAILED		     (VIOLET_ERROR_NETWORK_BEGIN -7)
#define VIOLET_ERROR_SOCKET_SEND_FAILED		     (VIOLET_ERROR_NETWORK_BEGIN -8)
#define VIOLET_ERROR_SOCKET_RECV_TIMEOUT		   (VIOLET_ERROR_NETWORK_BEGIN -9)
#define VIOLET_ERROR_SOCKET_SEND_TIMEOUT		   (VIOLET_ERROR_NETWORK_BEGIN -10)
#define VIOLET_ERROR_SOCKET_BIND_FAILED		     (VIOLET_ERROR_NETWORK_BEGIN -11)
#define VIOLET_ERROR_SOCKET_OPTION_FAILED		   (VIOLET_ERROR_NETWORK_BEGIN -12)
#define VIOLET_ERROR_SOCKET_EPOLL_CREATE_FAILED (VIOLET_ERROR_NETWORK_BEGIN -13)
#define VIOLET_ERROR_SOCKET_EPOLL_TIMEOUT		  (VIOLET_ERROR_NETWORK_BEGIN -14)
#define VIOLET_ERROR_SOCKET_EPOLL_CTRL_FAILRD	(VIOLET_ERROR_NETWORK_BEGIN -15)
#define VIOLET_ERROR_SOCKET_EPOLL_WAIT_FAILED	(VIOLET_ERROR_NETWORK_BEGIN -16)

//协议解析错误
#define VIOLET_ERROR_COMMAND_BEGIN					       (-200)	
#define VIOLET_ERROR_COMMAND_HEADER_CREAT_FAILED	 (VIOLET_ERROR_COMMAND_BEGIN-1)
#define VIOLET_ERROR_COMMAND_PLAYLOAD_CREAT_FAILED (VIOLET_ERROR_COMMAND_BEGIN-2)
#define VIOLET_ERROR_COMMAND_HEADER_PARSE_FAILED	 (VIOLET_ERROR_COMMAND_BEGIN-3)
#define VIOLET_ERROR_COMMAND_PLAYLOAD_PARSE_FAILED (VIOLET_ERROR_COMMAND_BEGIN-4)
#define VIOLET_ERROR_COMMAND_NOT_EXPIRE			       (VIOLET_ERROR_COMMAND_BEGIN-5)
#define VIOLET_ERROR_COMMAND_UNKNOWN				       (VIOLET_ERROR_COMMAND_BEGIN-6)
#define VIOLET_ERROR_COMMAND_FORMAT				         (VIOLET_ERROR_COMMAND_BEGIN-7)

//IO错误
#define VIOLET_ERROR_IO_BAGIN						          (-300)
#define VIOLET_ERROR_FILE_CREATE_FAILED			      (VIOLET_ERROR_IO_BAGIN -1)	
#define VIOLET_ERROR_FILE_OPEN_FAILED				      (VIOLET_ERROR_IO_BAGIN -2)
#define VIOLET_ERROR_FILE_EXISTED					        (VIOLET_ERROR_IO_BAGIN -3)
#define VIOLET_ERROR_FILE_READ_FAILED				      (VIOLET_ERROR_IO_BAGIN -4)
#define VIOLET_ERROR_FILE_WRITE_FAILRD				    (VIOLET_ERROR_IO_BAGIN -5)
#define VIOLET_ERROR_ACCESS_NOT_ENOUGH				    (VIOLET_ERROR_IO_BAGIN -6)
#define VIOLET_ERROR_FILE_SEEK_FAILED				      (VIOLET_ERROR_IO_BAGIN -7)
#define VIOLET_ERROR_FILE_END                     (VIOLET_ERROR_IO_BAGIN -8)
#define VIOLET_ERROR_FILE_NOT_EXISTED             (VIOLET_ERROR_IO_BAGIN -9)
#define VIOLET_ERROR_FILE_NOT_OPEN                (VIOLET_ERROR_IO_BAGIN -10)

//数据库错误
#define VIOLET_ERROR_DB_BAGIN						          (-400)
#define VIOLET_ERROR_CREATE_DB_FAILED				      (VIOLET_ERROR_DB_BAGIN -1)
#define VIOLET_ERROR_CREATE_TABLE_FAILED			    (VIOLET_ERROR_DB_BAGIN -2)
#define VIOLET_ERROR_INSERT_RECORD_FAILED		 	    (VIOLET_ERROR_DB_BAGIN -3)
#define VIOLET_ERROR_DELETE_RECORD_FAILED			    (VIOLET_ERROR_DB_BAGIN -4)
#define VIOLET_ERROR_SELECT_FAILED					      (VIOLET_ERROR_DB_BAGIN -5)
#define VIOLET_ERROR_UPDATE_FAILED					      (VIOLET_ERROR_DB_BAGIN -6)

#endif /*__VIOLET_ERROR_H__*/

